version: '3'

services:
    nodejs:
        image: raulc27/nodejs-sharks-image-demo
        container_name: nodejs
        restart: always
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=db
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        ports:
            - "81:8080"
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            - app-network
        command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon

    db:
      image: mongo:4.1.8-xenial
      container_name: db
      restart: always
      env_file: .env

      environment:
        - MONGO_INITTDB_ROOT_USERNAME=$MONGO_USERNAME
        - MONGO_INITTDB_ROOT_PASSWORD=$MONGO_PASSWORD
      volumes:
        - dbdata:/data/db
      networks:
        - app-network

networks:
    app-network:
        driver: bridge

volumes:
      dbdata:
  
